SCHOOLS = [
    "Acadia University",
    "Algonquin College",
    "Ashton College",
    "Assumption University",
    "Athabasca University",
    "Augustana University College",
    "British Columbia Institute of Technology",
    "British Columbia Open University",
    "William and Catherine Booth College",
    "Collège Boréal",
    "Bow Valley College",
    "Brandon University",
    "Brock University",
    "DeVry Institute of Technology",
    "Camosun College",
    "Capilano College",
    "University College of the Cariboo",
    "Carleton University",
    "Canadian College of Business & Computers",
    "Centennial College",
    "Canadian Mennonite University",
    "College of New Caledonia",
    "Columbia College",
    "Concordia University College of Alberta",
    "Concordia University",
    "Conestoga College",
    "College of the Rockies",
    "University of Moncton, Shippagan",
    "University of Moncton, Edmundston",
    "Dalhousie University",
    "Douglas College",
    "Durham College",
    "Emily Carr Institute of Art + Design",
    "École nationale d'administration publique, Université du Québec",
    "École de technologie supérieure, Université du Québec",
    "Fanshawe College",
    "First Nations University of Canada",
    "George Brown College",
    "École des Hautes Études Commerciales",
    "Humber College",
    "Huron University College",
    "Institut Armand-Frappier, Université du Québec",
    "Institut National de la Recherche Scientifique, Université du Québec",
    "Kingston College",
    "King's University College",
    "Kwantleen University College",
    "Lakehead University",
    "Langara College",
    "Lansbridge University",
    "Laurentian University of Sudbury",
    "MacEwan University",
    "Malaspina University College",
    "McGill University",
    "McMaster University",
    "Mount Saint Vincent University",
    "Mount Allison University",
    "Mount Royal College",
    "Northern Alberta Institute of Technology",
    "North Island College",
    "Nipissing University",
    "Northern Lights College",
    "Nova Scotia Agricultural College",
    "Nova Scotia College of Art and Design",
    "Nicola Valley Institute of Technology",
    "Ontario College of Art and Design",
    "Okanagan University College",
    "Dominican College of Philosophy and Theology",
    "Pacific International College",
    "École Polytechnique de Montréal, Université de Montréal",
    "Queen's University",
    "Quest University",
    "Redeemer College",
    "Regent College",
    "Royal Military College of Canada",
    "Royal Roads University",
    "Ryerson Polytechnic University",
    "Southern Alberta Institute of Technology",
    "Luther College",
    "Sauder School of Business",
    "University of Toronto, Scarborough",
    "Selkirk College",
    "Seneca College",
    "Simon Fraser University",
    "Sheridan College",
    "Saskatchewan Indian Federated College",
    "St. Clair College",
    "St. Francis Xavier University",
    "St. Mary's University",
    "St. Thomas University",
    "Télé-université, Université du Québec",
    "Trent University",
    "University of Trinity College",
    "Thompson Rivers University",
    "Trinity Western University",
    "University of Alberta",
    "University of British Columbia",
    "Bishop's University",
    "University of Calgary",
    "University College of Cape Breton",
    "University College of the Fraser Valley",
    "Memorial University of Newfoundland",
    "University of King's College",
    "Université Laval",
    "University of Lethbridge",
    "University of Manitoba",
    "University of Moncton",
    "Université de Montréal",
    "University of New Brunswick",
    "University of Northern British Columbia",
    "University of New Brunswick, Saint John",
    "University Canada West",
    "University of Guelph",
    "University of Ontario Institute of Technology",
    "University of Ottawa",
    "University of Prince Edward Island",
    "Université du Québec à Chicoutimi",
    "Université du Québec à Montréal",
    "Université du Québec à Rimouski",
    "Université du Québec en Abitibi-Témiscamingue",
    "Université du Québec en Outaouais",
    "Université du Québec à Trois-Rivières",
    "University of Québec",
    "Campion College",
    "University of Regina",
    "University of Saskatchewan",
    "Université de Sherbrooke",
    "University of St. Jerome's College",
    "St. Anne University",
    "University College of Saint-Boniface",
    "St. Paul University",
    "University of Sudbury",
    "University of Toronto, Mississauga",
    "University of St. Michael's College",
    "University of Toronto",
    "University of Victoria",
    "University of Waterloo",
    "University of Windsor",
    "University of Winnipeg",
    "Brescia College",
    "King's College",
    "University of Western Ontario",
    "Vancouver Community College",
    "Victoria University Toronto, University of Toronto",
    "Wilfrid Laurier University",
    "York University",
    "Yukon College"
  ]

PROGRAMS = [
    "Accounting",
    "African Studies",
    "Agriculture",
    "Agro-Environmental Sciences",
    "Anatomy",
    "Animal Biology",
    "Animal Health",
    "Animal Production",
    "Anthropology",
    "Applied Ecology",
    "Applied Mathematics",
    "Arabic Language",
    "Architecture",
    "Art History",
    "Behavioural Science",
    "Biochemistry",
    "Biodiversity",
    "Bioengineering",
    "Biology",
    "Biomedical Engineering",
    "Bioresource Engineering",
    "Biotechnology",
    "Business",
    "Canadian Ethnic",
    "Canadian Studies",
    "Catholic Studies",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classics",
    "Cognitive Science",
    "Communication Studies",
    "Composition",
    "Computer Engineering",
    "Computer Science",
    "Construction Engineering",
    "Dentistry",
    "Dietetics",
    "Earth",
    "Earth Sciences",
    "Earth System Science",
    "East Asian Cultural Studies",
    "East Asian Language",
    "East Asian Studies",
    "Ecology",
    "Economics",
    "Education",
    "Educational Psychology",
    "Electrical Engineering",
    "Engineering",
    "English",
    "Entrepreneurship",
    "Environment",
    "European Literature",
    "Farm Management",
    "Field Studies",
    "Finance",
    "Food Production",
    "Food Science",
    "Food Science & Nutritional Science",
    "Gender, Sexuality, Feminist, and Social Justice Studies",
    "General Science",
    "Geochemistry",
    "Geographic Information Systems",
    "Geography",
    "Geography: Urban Systems",
    "Geology",
    "German Language",
    "German Studies",
    "German Studies: Literature",
    "Global Food Security",
    "Health Geography",
    "Hispanic Studies",
    "Hispanic Studies: Languages",
    "Hispanic Studies: Literature",
    "History",
    "History and Philosophy of Science",
    "Human Nutrition",
    "Immunology",
    "Indigenous Studies",
    "Industrial Relations",
    "Information Systems",
    "Interdisciplinary Life Sciences",
    "International Development Studies",
    "International Management",
    "Investment Management",
    "Italian Studies",
    "Jewish Studies",
    "Kinesiology",
    "Kinesiology for Science Students",
    "Labour-Management Relations and Human Resources",
    "Law",
    "Liberal Arts",
    "Life Sciences",
    "Linguistics",
    "Management",
    "Managing for Sustainability",
    "Marketing",
    "Materials Engineering",
    "Mathematics",
    "Mathematics, Applied",
    "Mechanical Engineering",
    "Medicine",
    "Medieval Studies",
    "Meteorology",
    "Microbiology",
    "Mining Engineering",
    "Music",
    "Nanotechnology",
    "Natural History",
    "Neuroscience",
    "North American Studies",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Operations Management",
    "Organizational Behaviour",
    "Persian Language",
    "Pharmacology",
    "Philosophy",
    "Physical Therapy",
    "Physics",
    "Physiology",
    "Planetary Sciences",
    "Plant Biology",
    "Plant Production",
    "Political Science",
    "Professional Agrology",
    "Psychology",
    "Quebec Studies",
    "Religion",
    "Religious Studies",
    "Russian",
    "Social Studies of Medicine",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Statistics",
    "Teaching English as a Second Language",
    "Technological Entrepreneurship",
    "Turkish Language",
    "Urdu Language",
    "Wildlife Biology",
    "World Islamic & Middle East Studies",
    "World Religions"
]

COUNTRIES = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua & Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Ascension Island",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia & Herzegovina",
  "Botswana",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Canary Islands",
  "Cape Verde",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Central African Republic",
  "Ceuta & Melilla",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo - Brazzaville",
  "Congo - Kinshasa",
  "Cook Islands",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Diego Garcia",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Eurozone",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong SAR China",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau SAR China",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territories",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Réunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Samoa",
  "San Marino",
  "São Tomé & Príncipe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia & South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St. Barthélemy",
  "St. Helena",
  "St. Kitts & Nevis",
  "St. Lucia",
  "St. Martin",
  "St. Pierre & Miquelon",
  "St. Vincent & Grenadines",
  "Sudan",
  "Suriname",
  "Svalbard & Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad & Tobago",
  "Tristan da Cunha",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks & Caicos Islands",
  "Tuvalu",
  "U.S. Outlying Islands",
  "U.S. Virgin Islands",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United Nations",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wallis & Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]